# Generated by Django 3.0.4 on 2020-03-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('spec', models.TextField()),
                ('timings', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('qualif', models.TextField()),
            ],
        ),
    ]
