# Generated by Django 3.0.4 on 2020-04-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_username',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
