# Generated by Django 3.0.4 on 2020-04-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_appointment_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_username',
            field=models.CharField(max_length=100),
        ),
    ]
