# Generated by Django 3.0.4 on 2020-04-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20200406_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
