# Generated by Django 3.0.5 on 2020-04-17 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_appointment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_booked',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_treated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
